### ISSUE TITLE
☔ some issue

### ISSUE THREAD

**Issue by lahabana** [lahabana/sandbox#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Complex stuff!

### Acceptance Criteria

```[tasklist]
### Implementation
- [ ] Design
- [ ] Code
```

```[tasklist]
### Docs 
- [ ] https://github.com/lahabana/sandbox/issues/12
- [ ] https://github.com/lahabana/sandbox/issues/11
```
